Presentation/Models/ContentItemViewModels.cs
using Microsoft.AspNetCore.Html;
using System;

namespace Tcbcsl.Presentation.Models
{
    public class NewsItemModel
    {
        public DateTime StartDate { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
    }

    public class PageContentModel
    {
        public string Tag { get; set; }
        public string Title { get; set; }
        public HtmlString Content { get; set; }
    }
}

Presentation/Areas/Admin/Controllers/ContentItemController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Tcbcsl.Data;
using Tcbcsl.Data.Entities;
using Tcbcsl.Presentation.Areas.Admin.Models;
using Tcbcsl.Presentation.Helpers;

namespace Tcbcsl.Presentation.Areas.Admin.Controllers
{
    [AuthorizeRedirect(Roles = Roles.LeagueCommissioner)]
    [Route("Content")]
    public class ContentItemController : AdminControllerBase
    {
        public ContentItemController(TcbcslDbContext dbContext) : base(dbContext) { }

        #region List

        [Route("")]
        public ActionResult List()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Data()
        {
            var data = DbContext.PageContents
                                .OrderBy(pc => pc.PageContentId)
                                .ToList()
                                .Select(pc =>
                                        {
                                            var model = Mapper.Map<PageContentEditModel>(pc);
                                            model.UrlForEdit = Url.Action("Edit", new {id = model.PageContentId});

                                            return model;
                                        });

            return Json(data);
        }

        #endregion

        #region Create/Edit

        public ActionResult Create()
        {
            return View("Edit", new PageContentEditModel());
        }

        [HttpPost]
        public ActionResult Create(PageContentEditModel model)
        {
            var contentItem = Mapper.Map<PageContent>(model);
            DbContext.PageContents.Add(contentItem);
            DbContext.SaveChanges(User.Identity.GetUserId());

            return Redirect(model.UrlForReturn);
        }

        [Route("Edit/{id:int}")]
        public ActionResult Edit(int id)
        {
            var contentItem = DbContext.PageContents.SingleOrDefault(pc => pc.PageContentId == id);
            if (contentItem == null)
            {
                return NotFound();
            }

            var model = Mapper.Map<PageContentEditModel>(contentItem);

            return View(model);
        }

        [HttpPost]
        [Route("Edit/{id:int}")]
        public ActionResult Edit(int id, PageContentEditModel model)
        {
            var contentItem = DbContext.PageContents.SingleOrDefault(pc => pc.PageContentId == id);
            if (contentItem == null)
            {
                return NotFound();
            }

            Mapper.Map(model, contentItem);
            DbContext.SaveChanges(User.Identity.GetUserId());

            return Redirect(model.UrlForReturn);
        }

        #endregion
    }
}

Presentation/Areas/Manage/Controllers/ContentItemController.cs
using System.Web.Mvc;

namespace Tcbcsl.Presentation.Areas.Manage.Controllers
{
    [RouteArea("Manage")]
    [RoutePrefix("Content")]
    public class ContentItemController : Controller
    {
        [Route("")]
        public ActionResult List()
        {
            return View();
        }
    }
}

Presentation/Controllers/ContentItemController.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Tcbcsl.Data;
using Tcbcsl.Presentation.Models;

namespace Tcbcsl.Presentation.Controllers
{
    public class ContentItemController : TcbcslControllerBase
    {
        public ContentItemController(TcbcslDbContext dbContext) : base(dbContext) { }

        [Route("Content/{tag}")]
        public ActionResult PageContent(string tag)
        {
            var content = DbContext.PageContents
                                   .SingleOrDefault(pc => pc.PageTag == tag);

            return content == null
                       ? (ActionResult)NotFound()
                       : View(new PageContentModel
                              {
                                  Tag = content.PageTag,
                                  Title = content.Title,
                                  Content = new HtmlString(content.Content)
                              });
        }
    }
}

Presentation/Areas/Admin/Views/ContentItem/Edit.cshtml
@model PageContentEditModel
@{
    var title = Model.PageContentId == 0 ? "Create Content Item" : "Edit " + Model.Title;
    ViewBag.Title = title;
}
<div class="well">
    @using (Html.BeginForm("Edit", "ContentItem", FormMethod.Post, new {@class = "form-horizontal form-with-validation"}))
    {
        @Html.HiddenFor(m => m.PageContentId)

        <fieldset>
            <legend>@title</legend>
            @Html.EditorFor(m => m.PageTag)
            @Html.EditorFor(m => m.Title)
            @Html.EditorFor(m => m.Content)
            <partial name="_FormCancelSubmit" model="Model" />
        </fieldset>
    }
</div>

Presentation/Areas/Admin/Views/ContentItem/List.cshtml
@model PageContentEditModel
@{
    const string title = "Manage Content";
    ViewBag.Title = title;
}
<h2>@title</h2>
<partial name="_AdminListTable" model='new AdminListTableModel { ListItemName = "Content", CreateItemUrl = Url.Action("Create") }' />

@section scripts
{
    <script>
        var columns = [
            { 'data': 'PageContentId',           'title': '@Html.DisplayNameFor(m => m.PageContentId)',           'visible': false },
            { 'data': 'PageTag',                 'title': '@Html.DisplayNameFor(m => m.PageTag)' },
            { 'data': 'Title',                   'title': '@Html.DisplayNameFor(m => m.Title)' },
            { 'data': 'Content',                 'title': '@Html.DisplayNameFor(m => m.Content)',                                   'render': renderPartialContent },
            { 'data': 'AuditDetails.CreatedBy',  'title': '@Html.DisplayNameFor(m => m.AuditDetails.CreatedBy)',  'visible': false },
            { 'data': 'AuditDetails.Created',    'title': '@Html.DisplayNameFor(m => m.AuditDetails.Created)',    'visible': false, 'render': renderDate},
            { 'data': 'AuditDetails.ModifiedBy', 'title': '@Html.DisplayNameFor(m => m.AuditDetails.ModifiedBy)', 'visible': false },
            { 'data': 'AuditDetails.Modified',   'title': '@Html.DisplayNameFor(m => m.AuditDetails.Modified)',   'visible': false, 'render': renderDate},
            { 'data': 'UrlForEdit',                                                                                                 'render': renderEditLink }
        ];

        datatable_RenderList({
            'dataUrl': '@Url.Action("Data")',
            'columns': columns,
            'sorting': false,
            'paging': false
        });
    </script>
}