Presentation/Areas/Manage/Controllers/ContentItemController.cs
using System.Web.Mvc;

namespace Tcbcsl.Presentation.Areas.Manage.Controllers
{
    [RouteArea("Manage")]
    [RoutePrefix("Content")]
    public class ContentItemController : Controller
    {
        [Route("")]
        public ActionResult List()
        {
            return View();
        }
    }
}

Presentation/Controllers/ChurchController.cs
using AutoMapper;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Tcbcsl.Data;
using Tcbcsl.Presentation.Helpers;
using Tcbcsl.Presentation.Models;

namespace Tcbcsl.Presentation.Controllers
{
    public class ChurchController : TcbcslControllerBase
    {
        public ChurchController(TcbcslDbContext dbContext) : base(dbContext) { }

        [Route("Churches/{year:year?}")]
        public ActionResult Churches(int year = Consts.CurrentYear)
        {
            var churches = DbContext
                .Churches
                .Where(ch => ch.TeamYears.Any(ty => ty.Year == year && ty.DivisionYear.IsInLeague))
                .OrderBy(ch => ch.FullName)
                .ToList()
                .Select(ch => new ChurchListChurchModel
                              {
                                  Name = ch.FullName,
                                  Website = ch.Website.UrlToLink(),
                                  Information = string.IsNullOrWhiteSpace(ch.Information) ? null : new HtmlString(ch.Information),
                                  ContactInfo = Mapper.Map<ContactInfoModel>(ch)
                })
                .ToList();

            return View(new ChurchListModel
                        {
                            Year = year,
                            Churches = churches
                        });
        }
    }
}

Presentation/Controllers/CoachController.cs
using AutoMapper;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Tcbcsl.Data;
using Tcbcsl.Presentation.Models;

namespace Tcbcsl.Presentation.Controllers
{
    public class CoachController : TcbcslControllerBase
    {
        public CoachController(TcbcslDbContext dbContext) : base(dbContext) { }

        [Route("Coaches/{year:year?}")]
        public ActionResult Coaches(int year = Consts.CurrentYear)
        {
            var data = DbContext
                .DivisionYears
                .Where(dy => dy.Year == year && dy.IsInLeague)
                .Select(dy => new
                              {
                                  DivisionName = dy.Name,
                                  ConferenceSort = dy.ConferenceYear.Sort,
                                  DivisionSort = dy.Sort,
                                  Teams = dy.TeamYears
                                            .Select(ty => new
                                                          {
                                                              TeamId = ty.TeamId,
                                                              Year = year,
                                                              TeamName = ty.FullName,
                                                              HeadCoach = ty.HeadCoach
                                                          })
                                            .ToList()
                              })
                .ToList();

            var divisions = data
                .OrderBy(d => d.ConferenceSort)
                .ThenBy(d => d.DivisionSort)
                .Select(d => new CoachListDivisionModel
                              {
                                  DivisionName = d.DivisionName,
                                  Teams = d.Teams
                                            .Select(ty => new CoachListTeamModel
                                                          {
                                                              TeamId = ty.TeamId,
                                                              Year = year,
                                                              TeamName = ty.TeamName,
                                                              Coach = new CoachListCoachModel
                                                                      {
                                                                          Name = $"{ty.HeadCoach.FirstName} {ty.HeadCoach.LastName}",
                                                                          Comments = string.IsNullOrWhiteSpace(ty.HeadCoach.Comments)
                                                                                         ? null
                                                                                         : new HtmlString(ty.HeadCoach.Comments),
                                                                          ContactInfo = Mapper.Map<ContactInfoModel>(ty.HeadCoach)
                                                              }
                                                          })
                                            .ToList()
                              })
                .ToList();

            return View(new CoachListModel
                        {
                            Year = year,
                            Divisions = divisions
                        });
        }
    }
}

Presentation/Controllers/TeamController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Tcbcsl.Presentation.Models;
using Tcbcsl.Presentation.Services;

namespace Tcbcsl.Presentation.Controllers
{
    public class TeamController : ControllerBase
    {
        #region Constructor and Private Fields

        private static readonly List<StatsCategory> StatsCategories = new List<StatsCategory>
                                                                      {
                                                                          new StatsCategory {Name = "Batting Average (AVG)",     Field = "AVG", IsPercentage = true},
                                                                          new StatsCategory {Name = "Home Runs (HR)",            Field = "HR"},
                                                                          new StatsCategory {Name = "Walks (BB)",                Field = "BB"},
                                                                          new StatsCategory {Name = "Runs Batted In (RBI)",      Field = "RBI"},
                                                                          new StatsCategory {Name = "Runs (R)",                  Field = "R"},
                                                                          new StatsCategory {Name = "On-base + Slugging (OPS)",  Field = "OPS", IsPercentage = true}
                                                                      };

        private readonly ScheduleService _scheduleService;

        public TeamController()
        {
            _scheduleService = new ScheduleService(DbContext);
        }

        #endregion

        [Route("Teams/{year:year?}")]
        public ActionResult Teams(int year = Consts.CurrentYear)
        {
            var divisions = DbContext
                .DivisionYears
                .Where(dy => dy.Year == year && dy.IsInLeague)
                .OrderBy(dy => dy.ConferenceYear.Sort)
                .ThenBy(dy => dy.Sort)
                .Select(dy => new DivisionTeamsModel
                              {
                                  DivisionName = dy.Name,
                                  Teams = dy.TeamYears
                                            .OrderBy(ty => ty.FullName)
                                            .Select(ty => new TeamsListTeamModel
                                                          {
                                                              TeamId = ty.TeamId,
                                                              Year = year,
                                                              TeamName = ty.FullName
                                                          })
                                            .ToList()
                              })
                .ToList();

            return View(new TeamsListModel
                        {
                            Year = year,
                            Divisions = divisions
                        });
        }

        [Route("Team/{teamId}/{year:year?}")]
        public ActionResult View(int teamId, int year = Consts.CurrentYear)
        {
            var teamYear = DbContext
                .TeamYears
                .SingleOrDefault(ty => ty.TeamId == teamId && ty.Year == year);

            if (teamYear == null)
            {
                return HttpNotFound($"Team {teamId} not found for {year}.");
            }

            var model = new TeamViewModel
                        {
                            Year = teamYear.Year,
                            Years = teamYear.Team.TeamYears.Select(ty => ty.Year).OrderByDescending(y => y).ToArray(),
                            TeamId = teamYear.TeamId,
                            TeamName = teamYear.FullName,
                            DivisionName = teamYear.DivisionYear.Name,
                            ChurchId = teamYear.ChurchId,
                            ChurchName = teamYear.Church.FullName,
                            Coach = new TeamCoachModel
                                    {
                                        CoachId = teamYear.HeadCoachId,
                                        Year = year,
                                        Name = teamYear.HeadCoach.FullName,
                                        Comments = teamYear.HeadCoach.Comments,
                                        ContactInfo = Mapper.Map<ContactInfoModel>(teamYear.HeadCoach)
                                    },
                            Field = teamYear.Team.FieldInformation,
                            Comments = teamYear.Team.Comments,
                            NewsItems = new ContentService(DbContext).GetCurrentNews(teamYear.TeamId),
                            Schedule = new TeamScheduleModel
                                       {
                                           TeamId = teamYear.TeamId,
                                           Year = year,
                                           Games = _scheduleService.GetTeamSchedule(teamYear)
                                       }
                        };

            var teamGamesCount = teamYear.GameParticipants.Count(gp => gp.StatLines.Any());
            if (teamGamesCount > 0)
            {
                model.StatsLeaders = StatsCategories
                    .Select(cat => GetStatsCategoryLeader(cat, model.TeamId, year, (teamGamesCount + 1) / 2))
                    .ToList();
            }

            return View(model);
        }

        [Route("Team/{teamId}/ScheduleDownload")]
        public ActionResult ScheduleDownload(int teamId)
        {
            var teamYear = DbContext
                .TeamYears
                .SingleOrDefault(ty => ty.TeamId == teamId && ty.Year == Consts.CurrentYear);

            if (teamYear == null)
            {
                return HttpNotFound($"Team {teamId} not found for {Consts.CurrentYear}.");
            }

            var model = new TeamScheduleDownloadModel
            {
                Year = teamYear.Year,
                TeamId = teamYear.TeamId,
                TeamName = teamYear.FullName,
                Games = _scheduleService.GetTeamDownloadSchedule(teamYear)
            };

            Response.AddHeader("Content-Disposition", $"attachment; filename=\"{Url.Encode(teamYear.FullName)}-{Consts.CurrentYear}-Calendar.ics\"");
            return View(model);
        }

        private StatsLeaderModel GetStatsCategoryLeader(StatsCategory category, int teamId, int year, int teamGamesThreshhold)
        {
            var playerStats = KeyStatsForTeam(teamId, year);
            if (category.IsPercentage)
            {
                playerStats = playerStats.Where(ps => ps.Games >= teamGamesThreshhold);
            }

            var selectedValues = playerStats
                .Select(ps => new
                              {
                                  ps.PlayerId,
                                  ps.Name,
                                  Value = category.Field == "AVG"
                                              ? ps.AVG
                                              : category.Field == "HR"
                                                    ? ps.HR
                                                    : category.Field == "BB"
                                                          ? ps.BB
                                                          : category.Field == "RBI"
                                                                ? ps.RBI
                                                                : category.Field == "R"
                                                                      ? ps.Runs
                                                                      : ps.OPS
                              });

            var topValue = selectedValues
                .GroupBy(val => val.Value)
                .OrderByDescending(group => group.Key)
                .FirstOrDefault();

            var leader = new StatsLeaderModel
                         {
                             Year = year,
                             TeamId = teamId,
                             Category = category,
                             PlayerId = topValue == null || topValue.Key == 0 || topValue.Count() > 1 ? (int?)null : topValue.Single().PlayerId,
                             Name = topValue == null || topValue.Key == 0
                                        ? null
                                        : topValue.Count() > 1
                                              ? topValue.Count() + " tied"
                                              : topValue.Single().Name,
                             Value = topValue == null || topValue.Key == 0 ? (decimal?)null : topValue.Key
                         };

            return leader;
        }

        private class PlayerStats
        {
            // ReSharper disable InconsistentNaming
            public int PlayerId { get; set; }
            public string Name { get; set; }
            public int Games { get; set; }
            public decimal AVG { get; set; }
            public int HR { get; set; }
            public int BB { get; set; }
            public int RBI { get; set; }
            public int Runs { get; set; }
            public decimal OPS { get; set; }
            // ReSharper restore InconsistentNaming
        }

        private IQueryable<PlayerStats> KeyStatsForTeam(int teamId, int year)
        {
            return from line in DbContext.StatLines
                   where line.GameParticipant.TeamYear.TeamId == teamId
                         && line.GameParticipant.TeamYear.Year == year
                   group line by line.Player
                   into lineGroup
                   let plateAppearances = lineGroup.Sum(line => line.StatPlateAppearances)
                   let atBats = lineGroup.Sum(line => line.StatAtBats)
                   select new PlayerStats

Presentation/Areas/Admin/Views/Team/Edit.cshtml
@model TeamEditModel
@{
    var title = (Model.TeamId == 0 ? "Create" : "Edit") + " Team";
    ViewBag.Title = title;
}
<div class="well">
    @using (Html.BeginForm("Edit", "Team", FormMethod.Post, new { @class = "form-horizontal form-with-validation" }))
    {
        <fieldset>
            <legend>@title</legend>
            @Html.EditorFor(m => m.Church)
            @Html.EditorFor(m => m.TeamName)
            @Html.EditorFor(m => m.Division)
            @Html.EditorFor(m => m.HeadCoach)
            @Html.EditorFor(m => m.KeepsStats)
            @Html.EditorFor(m => m.HasPaid)
            @Html.EditorFor(m => m.Clinch)
            @Html.EditorFor(m => m.FieldInformation, new { IsReadonly = Model.YearModel.Year != Consts.CurrentYear })
            @Html.EditorFor(m => m.Comments, new { IsReadonly = Model.YearModel.Year != Consts.CurrentYear })
            <partial name="_FormCancelSubmit" model="Model" />
        </fieldset>
    }
</div>

Presentation/Areas/Admin/Views/Team/List.cshtml
@model TeamEditModel
@{
    const string title = "Manage Teams";
    ViewBag.Title = title + Model.YearModel.Year.AsTitleSuffix();
}
<partial name="_YearPartial" for="YearModel" />
<h2>@title</h2>
@using (Html.BeginForm())
{
    @Html.Hidden("Year", Model.YearModel.Year)
    <partial name="_AdminListTable" model='new AdminListTableModel { ListItemName = "Team", CreateItemUrl = Url.Action("Create") }' />
    <input type="submit" value="Save Changes" />
}

@section scripts
{
    <script>
        var divisionSelect;
        var clinchSelect;
        $.post('@Url.Action("ListDropdownData", new { year = Model.YearModel.Year })', function (data) {
            var html = $($.parseHTML(data))
            divisionSelect = html.filter('#Division_DivisionYearId');//.prop('outerHTML');
            clinchSelect = html.filter('#Clinch_ClinchChar');//.prop('outerHTML');
        });

        dtRowKey = 'TeamYearId';

        var columns = [
            { 'data': 'TeamId',                  'title': '@Html.DisplayNameFor(m => m.TeamId)',                  'visible':   false },
            { 'data': 'Conference',              'title': '@Html.DisplayNameFor(m => m.Conference)',                                    'render': renderConfDiv },
            { 'data': 'Division',                'title': '@Html.DisplayNameFor(m => m.Division)',                                      'render': renderDivDropdown },
            { 'data': 'FullName',                'title': '@Html.DisplayNameFor(m => m.FullName)' },
            { 'data': 'HeadCoach',               'title': '@Html.DisplayNameFor(m => m.HeadCoach)',                                     'render': {'_': 'FullName', 'sort': 'SortableName'} },
            { 'data': 'HasPaid',                 'title': '@Html.DisplayNameFor(m => m.HasPaid)',                                       'render': renderBoolCheckbox },
            { 'data': 'KeepsStats',              'title': '@Html.DisplayNameFor(m => m.KeepsStats)',                                    'render': renderBoolCheckbox },
            { 'data': 'Clinch',                  'title': '@Html.DisplayNameFor(m => m.Clinch)',                                        'render': renderClinchDropdown },
            { 'data': 'FieldInformation',        'title': '@Html.DisplayNameFor(m => m.FieldInformation)',        'visible':   false,   'render': renderPartialContent },
            { 'data': 'Comments',                'title': '@Html.DisplayNameFor(m => m.Comments)',                'visible':   false,   'render': renderPartialContent },
            { 'data': 'AuditDetails.CreatedBy',  'title': '@Html.DisplayNameFor(m => m.AuditDetails.CreatedBy)',  'visible':   false },
            { 'data': 'AuditDetails.Created',    'title': '@Html.DisplayNameFor(m => m.AuditDetails.Created)',    'visible':   false,   'render': renderDate },
            { 'data': 'AuditDetails.ModifiedBy', 'title': '@Html.DisplayNameFor(m => m.AuditDetails.ModifiedBy)', 'visible':   false },
            { 'data': 'AuditDetails.Modified',   'title': '@Html.DisplayNameFor(m => m.AuditDetails.Modified)',   'visible':   false,   'render': renderDate },
            { 'data': 'UrlForEdit',                                                                               'orderable': false,   'render': renderEditLinkWithHiddenId }
        ];

        datatable_RenderList({
            'dataUrl': '@Url.Action("Data", new {year = Model.YearModel.Year})',
            'columns': columns,
            'sorting': true,
            'paging': false,
            'order': [
                [findColumnIndex(columns, 'Conference'), 'asc'],
                [findColumnIndex(columns, 'Division'), 'asc'],
                [findColumnIndex(columns, 'FullName'), 'asc']
            ]
        });
    </script>
}

Presentation/Areas/Admin/Views/Team/ListDropdownData.cshtml
@model TeamListCommonEditModel

@Html.DropDownListFor(m => m.Division.DivisionYearId, Model.Division.ItemSelectList)
@Html.DropDownListFor(m => m.Clinch.ClinchChar, Model.Clinch.ItemSelectList)

Presentation/Areas/Admin/Views/Team/ListTeamYears.cshtml
@model TeamEditModel
@{
    var title = $"Transfer Teams to {Consts.CurrentYear}";
    ViewBag.Title = title + Model.YearModel.Year.AsTitleSuffix();
}
<partial name="_YearPartial" for="YearModel" />
<h2>@title</h2>
@using (Html.BeginForm("Transfer", "Team", FormMethod.Post))
{
    <partial name="_AdminListTable" model='new AdminListTableModel { CustomActionHeader = new HtmlString("<label><input class=\"select-all\" type=\"checkbox\" checked=\"checked\" /> Select/Deselect All</label>") }' />
    <input type="submit" value="Transfer Teams"/>
}

@section scripts
{
    <script>
        var columns = [
            { 'data': 'Conference',          'title': '@Html.DisplayNameFor(m => m.Conference)', 'orderable': false, 'render': renderConfDiv },
            { 'data': 'Division',            'title': '@Html.DisplayNameFor(m => m.Division)',   'orderable': false, 'render': renderConfDiv },
            { 'data': 'FullName',            'title': '@Html.DisplayNameFor(m => m.FullName)',   'orderable': false },
            { 'data': 'ExistsInCurrentYear',                                                     'orderable': false, 'render': renderTransfer }
        ];

        datatable_RenderList({
            'dataUrl': '@Url.Action("TeamYearData", new {year = Model.YearModel.Year})',
            'columns': columns,
            'sorting': true,
            'paging': false,
            'order': [
                [findColumnIndex(columns, 'Conference'), 'asc'],
                [findColumnIndex(columns, 'Division'), 'asc'],
                [findColumnIndex(columns, 'FullName'), 'asc']
            ]
        });
    </script>
}

Presentation/Areas/Admin/Views/Team/Manage.cshtml
@model TeamManageModel
@{
    var title = "Manage Team";
    ViewBag.Title = title;
}
@using (Html.BeginForm("Manage", "Team", FormMethod.Post, new { @class = "form-horizontal form-with-validation" }))
{
    <div class="well">
        <fieldset>
            <legend>
                <partial name="_FormLegendEdit" model="@Url.Action("Edit", new { id = Model.Team.TeamYearId })" />
                @Html.LabelFor(m => m.Team)
            </legend>
            @Html.EditorFor(m => m.Team.TeamName, new { IsReadOnly = true })
            @Html.EditorFor(m => m.Team.HasPaid, new { IsReadOnly = true })
            @Html.EditorFor(m => m.Team.FieldInformation, new { IsReadonly = true })
            @Html.EditorFor(m => m.Team.Comments, new { IsReadonly = true })
        </fieldset>
    </div>
    <div class="well">
        <fieldset>
            <legend>
                <partial name="_FormLegendEdit" model="@Url.Action("Edit", "Church", new { id = Model.Church.ChurchId })" />
                @Html.LabelFor(m => m.Church)
            </legend>
            @Html.EditorFor(m => m.Church.FullName, new { IsReadOnly = true })
            @Html.EditorFor(m => m.Church.DisplayName, new { IsReadOnly = true })
            @Html.EditorFor(m => m.Church.Address, new { IsReadOnly = true })
            @Html.EditorFor(m => m.Church.PhoneNumbers, new { IsReadOnly = true })
            @Html.EditorFor(m => m.Church.EmailAddress, new { IsReadOnly = true })
            @Html.EditorFor(m => m.Church.Website, new { IsReadOnly = true })
            @Html.EditorFor(m => m.Church.Information, new { IsReadOnly = true })
        </fieldset>
    </div>
    <div class="well">
        <fieldset>
            <legend>
                <partial name="_FormLegendEdit" model="@Url.Action("Edit", "Coach", new { id = Model.HeadCoach.CoachId })" />
                @Html.LabelFor(m => m.HeadCoach)
            </legend>
            @Html.EditorFor(m => m.HeadCoach.FirstName, new { IsReadOnly = true })
            @Html.EditorFor(m => m.HeadCoach.LastName, new { IsReadOnly = true })
            @Html.EditorFor(m => m.HeadCoach.EmailAddress, new { IsReadOnly = true })
            @Html.EditorFor(m => m.HeadCoach.PhoneNumbers, new { IsReadOnly = true })
            @Html.EditorFor(m => m.HeadCoach.Address, new { IsReadOnly = true })
            @Html.EditorFor(m => m.HeadCoach.Comments, new { IsReadOnly = true })
        </fieldset>
    </div>
}